### ISSUE TITLE
runtime-config containing auth keys should not be checked in

### ISSUE THREAD

**Issue by michelleN** [fermyon/ai-examples#37]
Is my assumption correct? We should not be checking in auth keys/runtime-config files to any repos?
https://github.com/fermyon/ai-examples/blob/main/helloworld-rs/runtime-config.toml

**Comment by radu-matei** [comment]
That is correct, yeah.

In fact, it might make sense to add the default runtime config file name/path to the templates' .gitignore.

Good catch!
